# Generated by Django 5.0.6 on 2024-06-30 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='/images/name-of-image.jpg', upload_to='images/'),
        ),
    ]
